- debug:
    var: nested_spec

- debug:
    var: registry_item 


- name: extend spec
  set_fact:
    nested_spec: "{{ nested_spec | combine({'ImagePullSecrets': [registry_item.name]}) }}"
  when: nested_spec.containers | selectattr('image', 'search', registry_item.address) | length > 0