- debug:
    var: nested_spec
  name: previous spec

- debug:
    var: registry_item 


# - name: extend spec
#   set_fact:
#     nested_spec: "{{ nested_spec | combine({'imagePullSecrets': [{'name': registry_item.name}]}) }}"
#   when: nested_spec.containers | selectattr('image', 'search', registry_item.address) | length > 0


- name: "Modify spec, if registry address is in container image"
  when: nested_spec.containers | selectattr('image', 'search', registry_item.address) | length > 0
  block:
    - name: "Create modified 'imagePullSecrets' list"
      set_fact:
        pull_secrets_list: "{{ nested_spec.imagePullSecrets | default([]) + [{'name': registry_item.name}] }}"

    - name: "Combine modified list with nested spec"
      set_fact:
        nested_spec: "{{ nested_spec | combine({'imagePullSecrets': pull_secrets_list }) }}"

- debug:
    var: nested_spec
  name: modified spec