- debug:
    var: nested_spec
  name: "Log previous spec"
  when: not (no_log | default(true))

- name: "Modify spec, if registry address is in container image"
  when: nested_spec.containers | selectattr('image', 'search', registry_item.address) | length > 0
  block:
    - name: "Create modified 'imagePullSecrets' list"
      no_log: "{{ no_log | default(true) }}"
      set_fact:
        pull_secrets_list: "{{ nested_spec.imagePullSecrets | default([]) + [{'name': registry_item.name}] }}"

    - name: "Combine modified list with nested spec"
      no_log: "{{ no_log | default(true) }}"
      set_fact:
        nested_spec: "{{ nested_spec | combine({'imagePullSecrets': pull_secrets_list }) }}"

- debug:
    var: nested_spec
  name: "Log modified specification"
  when: not (no_log | default(true))