dependencies: []
galaxy_info:
  author: Benjamin Goetz
  namespace: fabos.k3s
  role_name: use
  description: Use role for k3s
  company: Fraunhofer IPA

  license: license (MIT)

  min_ansible_version: 2.1

  platforms:
    - name: CentOS
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04
        - 21.10
        - 22.04

  galaxy_tags: [k3s, docker-compose, deploy, undeploy]
