---
- name: Converge - Setup K3s Server
  hosts: k3s_server
  gather_facts: yes
  become: yes
  tasks:
    - name: Include K3s setup_server.yml
      include_role:
        name: setup
        tasks_from: install.yml