---
- name: Converge - Install K3s single
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Include K3s setup
      ansible.builtin.include_role:
        name: ../../../
        tasks_from: install.yml
