---
- name: Verify - K3s
  hosts: all
  gather_facts: false
  become: true
  vars:
    expected_line_count: 2
  tasks:
    - name: Get stat of kubectl
      ansible.builtin.stat:
        path: /usr/local/bin/kubectl
      register: kubectl

    - name: Assert kubectl exists
      ansible.builtin.assert:
        that: kubectl.stat.exists

    - name: Get Cluster info
      ansible.builtin.shell: "/usr/local/bin/kubectl get node"
      register: output_get_node
      until: output_get_node.stdout_lines | length == expected_line_count
      retries: 10

    - name: Debug output of kubectl get node
      ansible.builtin.debug:
        var: output_get_node.stdout_lines

    - name: Assert output line count
      ansible.builtin.assert:
        that: output_get_node.stdout_lines | length == expected_line_count
