---
- name: "Check required variables"
  assert:
    that: "{{ item.name }} is defined"
    fail_msg: "Missing variable '{{ item.name }}': {{ item.description }}"
  with_items:
    - { name: "service_id",                description: "Id of the service instance that will be deployed." }
    - { name: "manifest_file",             description: "Content of the manifest file." }

- name: "Create namespace"
  kubernetes.core.k8s:
    name: "{{ service_id }}"
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  register: create_ns
  until: not create_ns.failed
  retries: 10

- name: "Process every item in manifest definition"
  include_tasks: helper/process_deploy_definition.yml
  loop: "{{ manifest_file | from_yaml_all }}"
