namespace: fabos

name: k3s_single

version: 1.0.0

readme: README.md

authors:
- Benjamin Goetz - Fraunhofer IPA

description: The collection provides playbooks for installing and uninstalling of k3s on target hosts and deploying and undeploying of container based on kubernetes manifest files (see "use" role). The additional "inventory_helper" role helps to create an inventory based on information available in the context of the FabOS Service Lifecycle Management (SLM).

license:
- Apache 2.0

license_file: 'LICENSE'

tags: [k3s, docker-compose, install, uninstall, deploy, undeploy]

dependencies: {}

repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker

build_ignore: []

