---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demonstrate-envars
  name: kubernetes-so-demo
spec:
  template:
    spec:
      containers:
      - env:
        - name: DEMO_GREETING
          value: Hello from the environment
        - name: DEMO_FAREWELL
          value: Such a sweet sorrow
        image: gcr.io/google-samples/node-hello:1.0
        name: hello-app-server
      - env:
        - name: DEMO_GREETING
          value: Hello from the environment
        - name: DEMO_FAREWELL
          value: Such a sweet sorrow
        image: gcr.io/google-samples/node-hello:1.0
        name: hello-app-server-2
      ImagePullSecrets:
      - aaa