---
- name: Verify - K3s
  hosts: k3s_server[0]
  gather_facts: yes
  become: yes

  tasks:
    - name: Get stat of kubectl
      stat:
        path: /usr/local/bin/kubectl
      register: kubectl

    - assert:
        that: kubectl.stat.exists

    - name: Get Cluster info
      ansible.builtin.shell: "/usr/local/bin/kubectl get node"
      register: output_get_node
      until: output_get_node.stdout_lines | length == 5
      retries: 60

    - debug:
        var: output_get_node.stdout_lines

    - assert:
        that: output_get_node.stdout_lines | length == 5