---
roles:
  - name: ipa-big.molecule_openstack
    version: 1.0.10
  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-inventory-helper"
    scm: git
    version: 1.0.0
    name: inventory_helper
