---
- name: Verify - Undeploy
  hosts: k3s_server
  run_once: yes
  gather_facts: no
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Include vars file
      include_vars:
        file: ./vars/main.yml

    - name: Get Namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: "{{ service_id }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
      register: ns_info
      until: ns_info.resources | length == 0
      retries: 60

    - assert:
        that: ns_info.resources | length == 0

    - name: Get Service
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        namespace: "{{ service_id }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
      register: service_info

    - assert:
        that: service_info.resources | length == 0

    - name: Get Deployment
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Deployment
        namespace: "{{ service_id }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
      register: deployment_info

    - assert:
        that: deployment_info.resources | length == 0

    - name: Get PVC
      kubernetes.core.k8s_info:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: "{{ service_id }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
      register: pvc_info

    - assert:
        that: pvc_info.resources | length == 0