---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: centos8-1
    template_name: centos-stream-8
    groups:
      - k3s_server

  - name: centos8-2
    template_name: centos-stream-8
    groups:
      - k3s_server

  - name: centos8-3
    template_name: centos-stream-8
    groups:
      - k3s_server

  - name: centos8-4
    template_name: centos-stream-8
    groups:
      - k3s_agent
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ../default-install/converge.yml
    destroy: ../default/destroy.yml
    converge: ../default-uninstall/converge.yml
    verify: ../default-uninstall/verify.yml

verifier:
  name: ansible
