---
- name: Converge - Uninstall k3s server
  hosts: k3s_server
  gather_facts: true
  become: true
  tasks:
    - name: Include K3s uninstall.yml
      ansible.builtin.include_role:
        name: setup
        tasks_from: uninstall.yml
