---
- name: Converge - Uninstall k3s server
  hosts: k3s_server
  gather_facts: yes
  become: yes
  tasks:
    - name: Include K3s uninstall.yml
      include_role:
        name: setup
        tasks_from: uninstall.yml