---
- name: Install packages (Ubuntu)
  when: ansible_facts['distribution'] == 'Ubuntu'
  ansible.builtin.include_tasks: dist-specific/install_packages_ubuntu.yml

- name: Install packages (Debian)
  when: ansible_facts['distribution'] == 'Debian'
  ansible.builtin.include_tasks: dist-specific/install_packages_debian.yml

- name: Install packages (CentOS)
  when: ansible_facts['distribution'] == 'CentOS'
  ansible.builtin.include_tasks: dist-specific/install_packages_centos.yml
