---
# Dependency management (download roles/collections)
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml

platforms:
  - name: centos7
    image_name: CentOS 7 64-bit (Ansible)

  - name: centos8
    image_name: CentOS 8 64-bit (Ansible)

  - name: centos9
    image_name: CentOS 9 Stream 64-bit

  - name: centos10
    image_name: CentOS 10 Stream 64-bit

ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"

  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --diff
        - --force-handlers
      ansible_navigator:
        - --mode stdout
        - --pull-policy missing
        - --execution-environment-image ghcr.io/ansible/community-ansible-dev-tools:latest

  playbooks:
    create: ../default/create.yml
    converge: ../default-install/converge.yml
    destroy: ../default/destroy.yml
    verify: ../default-install/verify.yml

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
