---
- name: Verify - K3s
  hosts: k3s_server:k3s_agent
  gather_facts: yes
  become: yes

  tasks:
    - name: Get Cluster info
      ansible.builtin.shell: "/usr/local/bin/kubectl get node"
      failed_when: false
      register: output_get_node

    - assert:
        that: output_get_node.rc != 0

    - debug:
        var: output_get_node.stderr