---
- name: Create cgroup memory (Raspbian only)
  when:
    - ansible_facts['lsb.id'] is defined
    - ansible_facts['lsb.id'] == 'Raspbian'
  ansible.builtin.include_tasks: helper/create_cgroup_memory.yml

- name: Include tasks for installing packages
  ansible.builtin.include_tasks: helper/install_packages.yml

- name: Include tasks file for downloading install script
  ansible.builtin.include_tasks: helper/download_install_script.yml

- name: Check if token file exists
  ansible.builtin.stat:
    path: /var/lib/rancher/k3s/server/node-token
  register: token_file

- name: Set K3s version (Ubuntu 20.04)
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution_version'] is version('20.04', '<=')
  ansible.builtin.set_fact:
    k3s_version: "v1.34.7+k3s1"

- name: Set K3s version (CentOS < 9)
  when:
    - ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['distribution_version'] is version('9', '<')
  ansible.builtin.set_fact:
    k3s_version: "v1.34.7+k3s1"

- name: Run install script
  ansible.builtin.shell: "sh {{ install_script_dest }}"
  register: output_install
  when: not token_file.stat.exists
  environment:
    INSTALL_K3S_EXEC: "server --cluster-init --node-external-ip {{ ansible_host }} {{ k3s_exec | default('') }}"
    INSTALL_K3S_VERSION: "{{ k3s_version | default('v1.36.0+k3s1') }}"
    K3S_NODE_NAME: k3s-single-node
